# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07cdb28b76ed20a2bb715bb950c91819eda2592601beb68c71291a199fb64325a21e3dee7c477ac6405d704dc0bdd6c96014a7907062cbda30a1d5730d68fd95

test:
  secret_key_base: 884a80723910b6c805875bc85c20a936efc3e522b4344680176d49c9ea13b7b5ba0ece2a7883a19fb4c5475f97508c4ed63e8ffdcc3c10e3cd5242a71bfd6893

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
